export const top5CountdownDefaultContent = {
  brand: {
    name: 'Top 5 Countdown',
    tagline: 'Tech Innovations',
    logoUrl: '',
    primaryColor: '#FFD60A',
    accentColor: '#FF3B5C',
  },
  product: {
    name: 'TOP 5 TECH INNOVATIONS',
    description: 'Discover the top 5 tech innovations shaping our world.',
    imageUrl: '',
  },
  cta: {
    text: 'Watch Full List',
    subtext: 'More rankings coming soon',
    url: '',
  },
  headline: 'TOP 5',
  listTitle: 'TOP 5 TECH INNOVATIONS',
  introText: 'Discover the top 5 tech innovations shaping our world.',
  category: 'Technology',
  item5Title: 'Smart Glasses',
  item5Description: 'Smart glasses are bringing digital information directly into our everyday view.',
  item5Image: '',
  item5Statistic: 0,
  item5StatisticLabel: '',
  item5AccentText: '#5',
  item4Title: 'AI Assistants',
  item4Description: 'AI assistants are changing how people work, communicate and access information.',
  item4Image: '',
  item4Statistic: 0,
  item4StatisticLabel: '',
  item4AccentText: '#4',
  item3Title: 'Electric Vehicles',
  item3Description: 'Electric vehicles are transforming transportation with cleaner and smarter technology.',
  item3Image: '',
  item3Statistic: 0,
  item3StatisticLabel: '',
  item3AccentText: '#3',
  item2Title: 'Robotics',
  item2Description: 'Advanced robots are becoming essential across factories, logistics and everyday life.',
  item2Image: '',
  item2Statistic: 0,
  item2StatisticLabel: '',
  item2AccentText: '#2',
  item1Title: 'Generative AI',
  item1Description: 'Generative AI is transforming software, creativity and the way businesses work.',
  item1Image: '',
  item1Statistic: 0,
  item1StatisticLabel: '',
  item1AccentText: '#1',
};

export type Top5CountdownDefaultContent = typeof top5CountdownDefaultContent;
