export const top5CountdownDefaultContent = {
  brand: {
    name: 'Top 5 Countdown',
    tagline: 'Weekly Ranking',
    logoUrl: '',
    primaryColor: '#FFD60A',
    accentColor: '#FF3B5C',
  },
  product: {
    name: 'The Ultimate Ranking',
    description: 'Discover the top picks that define this week\'s list.',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ce9f5?q=80&w=1000&auto=format&fit=crop',
  },
  cta: {
    text: 'Watch Full List',
    subtext: 'Rankings update every week',
    url: '',
  },
  headline: 'TOP 5',
  listTitle: 'This Week\'s Top 5',
  introText: 'Discover the top 5 picks that define this week\'s list.',
  category: 'Trending',
  item1Title: 'Mountain Explorer Pro',
  item1Description: 'The ultimate gear for serious hikers and climbers.',
  item1Image: 'https://images.unsplash.com/photo-1551632811-561732d5460e?q=80&w=800&auto=format&fit=crop',
  item1Statistic: 87,
  item1StatisticLabel: 'Adventure Score',
  item1AccentText: 'Best Gear',
  item2Title: 'Urban Commuter Elite',
  item2Description: 'Navigate the city with style and efficiency.',
  item2Image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=800&auto=format&fit=crop',
  item2Statistic: 92,
  item2StatisticLabel: 'Urban Score',
  item2AccentText: 'City Pick',
  item3Title: 'Tech Innovator X',
  item3Description: 'Next-generation tech that changes how you work.',
  item3Image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
  item3Statistic: 95,
  item3StatisticLabel: 'Tech Score',
  item3AccentText: 'Editor\'s Choice',
  item4Title: 'Wellness Essential',
  item4Description: 'Premium health and wellness products for daily life.',
  item4Image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
  item4Statistic: 97,
  item4StatisticLabel: 'Wellness Score',
  item4AccentText: 'Top Rated',
  item5Title: 'Aurora Smart Watch',
  item5Description: 'The smartest wearable for the modern lifestyle.',
  item5Image: 'https://images.unsplash.com/photo-1546868871-af0de0ae72be?q=80&w=800&auto=format&fit=crop',
  item5Statistic: 99,
  item5StatisticLabel: 'Overall Score',
  item5AccentText: '#1 Pick',
};

export type Top5CountdownDefaultContent = typeof top5CountdownDefaultContent;
